# https://www.biorxiv.org/content/10.1101/2020.03.23.000356v1.full
# https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE115478


MAX_THREADS: 8


project: template # your project name here
fasta: /media/mlawlor/work/dmel-all-chromosome-r6.22.fasta
gtf: /media/mlawlor/work/dmel-all-r6.22.gtf
samples:
  samp1: # your own assigned name for this sample
    fastq: # uri to fastq or fastq.gz. can be single or paired end
      r1:
        - gs://sra-pub-src-7/SRR7276830/B5_TCP_R1.fastq.gz
