# https://www.biorxiv.org/content/10.1101/2020.03.23.000356v1.full
# https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE115478


MAX_THREADS: 8

fasta: /scratch/mal456/20200105_elr/genome/fasta/genome.fa
gtf: /scratch/mal456/20200105_elr/genome/genes/genes.gtf

samples:
  larval_testes_cleaned_papain_01: # your own assigned name for this sample
    fastq: # uri to fastq or fastq.gz. can be single or paired end
      r1:
      - ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR727/000/SRR7276830/SRR7276830.fastq.gz
  larval_testes_papain_02:
    fastq:
      r1:
      - ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR727/001/SRR7276831/SRR7276831.fastq.gz
  larval_testes_papain_03:
    fastq:
      r1:
      - ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR727/002/SRR7276832/SRR7276832.fastq.gz
  larval_testes_papain_04:
    fastq:
      r1:
      - ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR727/003/SRR7276833/SRR7276833.fastq.gz